# Generated by Django 6.0 on 2025-12-07 08:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100, verbose_name='Cable Identifier (e.g., C-1)')),
                ('fiber_count', models.IntegerField(verbose_name='Fiber Count')),
                ('size_mm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Size (mm)')),
                ('distance_km', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Distance (km)')),
            ],
            options={
                'verbose_name': 'Cable Register Entry',
                'verbose_name_plural': 'Cable Register Entries',
            },
        ),
        migrations.CreateModel(
            name='PopLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'PoP Location',
                'verbose_name_plural': 'PoP Locations',
            },
        ),
        migrations.CreateModel(
            name='Manhole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manhole_id', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('manhole_type', models.CharField(choices=[('MH', 'Manhole'), ('JNT', 'Joint Closure'), ('OTH', 'Other')], default='MH', max_length=5)),
                ('manhole_condition', models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=10)),
                ('joint_condition', models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=10)),
                ('is_completed', models.BooleanField(default=False, verbose_name='Splicing Completed at this location')),
                ('incoming_cable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminating_manholes', to='splicing.cable', verbose_name='Incoming Cable (from previous point)')),
            ],
            options={
                'verbose_name': 'Manhole/Joint',
                'verbose_name_plural': 'Manholes/Joints',
            },
        ),
        migrations.CreateModel(
            name='SplicePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spliced_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Spliced Date/Time')),
                ('power_level_dbm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Power Level (dBm)')),
                ('splice_loss_db', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Splice Loss (dB)')),
                ('required_action', models.CharField(choices=[('NONE', 'None'), ('CLEAN', 'Clean/Retry'), ('REPLACE', 'Replace Fiber/Connector'), ('RECUT', 'Recut Splice')], default='NONE', max_length=10, verbose_name='Required Action')),
                ('comments', models.TextField(blank=True)),
                ('cable_a', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='splice_a_set', to='splicing.cable', verbose_name='Cable A (From)')),
                ('cable_b', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='splice_b_set', to='splicing.cable', verbose_name='Cable B (To)')),
                ('manhole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splice_details', to='splicing.manhole')),
            ],
            options={
                'verbose_name': 'Splice Performance Record',
                'verbose_name_plural': 'Splice Performance Records',
            },
        ),
        migrations.CreateModel(
            name='SplicingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=50, unique=True)),
                ('project_code', models.CharField(max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=100, verbose_name='Customer Name')),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2)),
                ('status', models.CharField(choices=[('NEW', 'New Job'), ('MANAGER_ASSIGNED', 'Assigned to Manager'), ('FE_ASSIGNED', 'Assigned to Field Engineer'), ('IN_PROGRESS', 'Splicing In Progress'), ('COMPLETED', 'Splicing Completed')], default='NEW', max_length=20)),
                ('description', models.TextField(verbose_name='Job Scope/Description')),
                ('port_number', models.CharField(blank=True, max_length=20, verbose_name='Target Port Number')),
                ('street_address', models.CharField(max_length=255, verbose_name='Street Address/Block No.')),
                ('area', models.CharField(max_length=100, verbose_name='Area/Sub-Area')),
                ('neighbourhood', models.CharField(max_length=100, verbose_name='Neighbourhood/Zone')),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(default='Zambia', max_length=50)),
                ('contractor', models.CharField(blank=True, max_length=100, verbose_name='Contractor Name')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('required_completion_date', models.DateField(blank=True, null=True)),
                ('target_duration_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Expected time to complete the job, in hours.', max_digits=5, null=True, verbose_name='Target Duration (Hours)')),
                ('comment', models.TextField(blank=True)),
                ('trace_attachment', models.FileField(blank=True, null=True, upload_to='job_traces/')),
                ('splicing_picture', models.ImageField(blank=True, null=True, upload_to='splicing_photos/')),
                ('assigned_fe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fe_jobs', to=settings.AUTH_USER_MODEL)),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_jobs', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('pop_location_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='splicing.poplocation', verbose_name='Target PoP Location')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager')),
            ],
            options={
                'verbose_name': 'Splicing Job',
                'verbose_name_plural': 'Splicing Jobs',
            },
        ),
        migrations.AddField(
            model_name='manhole',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manholes', to='splicing.splicingjob'),
        ),
        migrations.AddField(
            model_name='cable',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cables', to='splicing.splicingjob'),
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('pop_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='splicing.poplocation')),
            ],
            options={
                'verbose_name_plural': 'Switches',
                'unique_together': {('pop_location', 'name')},
            },
        ),
        migrations.AddField(
            model_name='splicingjob',
            name='switch_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='splicing.switch', verbose_name='Target Switch'),
        ),
        migrations.AlterUniqueTogether(
            name='manhole',
            unique_together={('job', 'manhole_id')},
        ),
        migrations.AlterUniqueTogether(
            name='cable',
            unique_together={('job', 'identifier')},
        ),
    ]
