# Generated by Django 6.0 on 2025-12-08 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splicing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splicingjob',
            name='area',
        ),
    ]
