# Generated by Django 6.0 on 2025-12-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splicing', '0003_alter_manhole_latitude_alter_manhole_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splicingjob',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='splicingjob',
            name='country',
            field=models.CharField(blank=True, default='Zambia', max_length=50),
        ),
        migrations.AlterField(
            model_name='splicingjob',
            name='description',
            field=models.TextField(blank=True, verbose_name='Job Scope/Description'),
        ),
        migrations.AlterField(
            model_name='splicingjob',
            name='neighbourhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Neighbourhood/Zone'),
        ),
        migrations.AlterField(
            model_name='splicingjob',
            name='project_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='splicingjob',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='splicingjob',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Street Address/Block No.'),
        ),
    ]
