# Generated by Django 6.0 on 2025-12-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splicing', '0005_alter_splicingjob_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splicingjob',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Job'), ('MANAGER_ASSIGNED', 'Assigned to Manager'), ('FE_ASSIGNED', 'Assigned to Field Engineer'), ('IN_PROGRESS', 'Splicing In Progress'), ('COMPLETED', 'Splicing Completed'), ('CLOSED', 'Job Closed/Finalized')], default='NEW', max_length=20),
        ),
    ]
