# Generated by Django 6.0 on 2025-12-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splicing', '0007_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splicingjob',
            name='contractor',
        ),
        migrations.AddField(
            model_name='splicingjob',
            name='civil_contractor_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Civil Works Contractor'),
        ),
        migrations.AddField(
            model_name='splicingjob',
            name='splicing_contractor_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Splicing Contractor Company Name'),
        ),
    ]
