# Generated by Django 6.0 on 2025-12-13 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splicing', '0008_remove_splicingjob_contractor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='splicingjob',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Job'), ('MANAGER_ASSIGNED', 'Assigned to Manager'), ('FE_ASSIGNED', 'Assigned to Field Engineer'), ('IN_PROGRESS', 'Splicing In Progress'), ('COMPLETED', 'Splicing Completed'), ('SD_PENDING', 'Ready for Service Provisioning'), ('PROVISIONED', 'Service Provisioned (Complete)'), ('CLOSED_ARCHIVED', 'Job Closed and Archived')], default='NEW', max_length=20),
        ),
        migrations.CreateModel(
            name='ProvisioningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Assigned IP Address')),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, verbose_name='Default Gateway')),
                ('service_description', models.TextField(help_text='e.g., Customer Circuit ID, Service Name', verbose_name='Service Description')),
                ('service_type', models.CharField(choices=[('LEASING', 'Fibre Leasing'), ('INTERNET', 'Dedicated Internet'), ('VPN', 'MPLS VPN'), ('OTHER', 'Other')], default='INTERNET', max_length=50, verbose_name='Type of Service')),
                ('capacity_mbps', models.IntegerField(blank=True, null=True, verbose_name='Capacity (Mbps)')),
                ('configured_on', models.DateTimeField(auto_now_add=True)),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Provisioned By')),
                ('splicing_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_record', to='splicing.splicingjob')),
            ],
            options={
                'verbose_name': 'Service Provisioning Record',
                'verbose_name_plural': 'Service Provisioning Records',
            },
        ),
    ]
