# Generated by Django 6.0 on 2025-12-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splicing', '0009_alter_splicingjob_status_provisioningrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provisioningrecord',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='provisioningrecord',
            name='service_description',
        ),
        migrations.AddField(
            model_name='provisioningrecord',
            name='final_service_notes',
            field=models.TextField(blank=True, help_text='Detailed description of the service configured (e.g., bandwidth, routing details)...', null=True, verbose_name='Final Service Notes/Circuit ID'),
        ),
        migrations.AddField(
            model_name='provisioningrecord',
            name='gateway_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Default Gateway IP'),
        ),
        migrations.AddField(
            model_name='provisioningrecord',
            name='subnet_mask',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Subnet Mask (e.g., 255.255.255.0)'),
        ),
        migrations.AddField(
            model_name='provisioningrecord',
            name='vlan_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Assigned VLAN ID'),
        ),
    ]
