# Generated by Django 6.0 on 2025-12-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splicing', '0011_alter_splicingjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='splicingjob',
            name='closeout_comment',
            field=models.TextField(blank=True, verbose_name='Manager Closeout Comment'),
        ),
    ]
