# Generated by Django 6.0 on 2025-12-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splicing', '0013_alter_splicingjob_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manhole',
            name='incoming_cable',
        ),
        migrations.RemoveField(
            model_name='spliceperformance',
            name='cable_b',
        ),
        migrations.RemoveField(
            model_name='spliceperformance',
            name='cable_a',
        ),
        migrations.AlterUniqueTogether(
            name='manhole',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='manhole',
            name='job',
        ),
        migrations.RemoveField(
            model_name='spliceperformance',
            name='manhole',
        ),
        migrations.AddField(
            model_name='splicingjob',
            name='alt_contact_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Alternative Contact Number'),
        ),
        migrations.AddField(
            model_name='splicingjob',
            name='alt_contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Alternative Contact Person'),
        ),
        migrations.AddField(
            model_name='splicingjob',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Primary Contact Number'),
        ),
        migrations.AddField(
            model_name='splicingjob',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Primary Contact Person'),
        ),
        migrations.AlterField(
            model_name='splicingjob',
            name='status',
            field=models.CharField(choices=[('NEW', 'New/Draft Job'), ('MANAGER_ASSIGNED', 'Assigned to Manager'), ('FE_ASSIGNED', 'Assigned to Field Engineer'), ('IN_PROGRESS', 'Splicing In Progress'), ('SD_PENDING', 'Ready for Service Provisioning'), ('PROVISIONED', 'Service Provisioned (Complete)'), ('CLOSED_ARCHIVED', 'Job Closed and Archived'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20),
        ),
        migrations.DeleteModel(
            name='Cable',
        ),
        migrations.DeleteModel(
            name='Manhole',
        ),
        migrations.DeleteModel(
            name='SplicePerformance',
        ),
    ]
