# Generated by Django 6.0 on 2025-12-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splicing', '0014_remove_manhole_incoming_cable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splicingjob',
            name='status',
            field=models.CharField(choices=[('NEW', 'New/Draft Job'), ('MANAGER_ASSIGNED', 'Assigned to Manager'), ('FE_ASSIGNED', 'Assigned to Field Engineer'), ('IN_PROGRESS', 'Splicing In Progress'), ('ON_HOLD', 'Job On Hold'), ('SD_PENDING', 'Ready for Service Provisioning'), ('PROVISIONED', 'Service Provisioned (Complete)'), ('CLOSED_ARCHIVED', 'Job Closed and Archived'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20),
        ),
    ]
