# Generated by Django 6.0 on 2025-12-17 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splicing', '0015_alter_splicingjob_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='splicingjob',
            options={'permissions': [('can_view_advanced_report', 'Can view the advanced dashboard and exports')], 'verbose_name': 'Splicing Job', 'verbose_name_plural': 'Splicing Jobs'},
        ),
        migrations.AlterField(
            model_name='provisioningrecord',
            name='capacity_mbps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provisioningrecord',
            name='configured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='provisioningrecord',
            name='final_service_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provisioningrecord',
            name='gateway_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provisioningrecord',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provisioningrecord',
            name='service_type',
            field=models.CharField(choices=[('LEASING', 'Fibre Leasing'), ('INTERNET', 'Dedicated Internet'), ('VPN', 'MPLS VPN'), ('OTHER', 'Other')], default='INTERNET', max_length=50),
        ),
        migrations.AlterField(
            model_name='provisioningrecord',
            name='subnet_mask',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='provisioningrecord',
            name='vlan_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='splicingjob',
            name='civil_contractor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='splicingjob',
            name='neighbourhood',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='splicingjob',
            name='pop_location_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='splicing.poplocation'),
        ),
        migrations.AlterField(
            model_name='splicingjob',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='splicingjob',
            name='splicing_contractor_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='splicingjob',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='splicingjob',
            name='switch_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='splicing.switch'),
        ),
        migrations.AlterField(
            model_name='splicingjob',
            name='target_duration_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
