"""
Django settings for splicing_tracker project.

Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-&$4sxo3ws(x)p^^slwy_o&nns7unys^yh8#us7^w2742yegay*'

DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # --- Local Apps ---
    'splicing',
    # --- Third-Party Apps ---
    'crispy_forms',
    'crispy_tailwind',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'splicing_tracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # DIRS points to the global templates folder (e.g., for base.html, login.html)
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'splicing_tracker.wsgi.application'


# Database
DATABASES = {
    'default': dj_database_url.config(
        # This will be used if DATABASE_URL is not found (Local Dev)
        default='sqlite:///db.sqlite3',
        conn_max_age=600,
        ssl_require=not DEBUG # Ensures secure connection in production
    )
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

# Correct Timezone for Zambia, or use UTC if preferable for production servers
TIME_ZONE = 'Africa/Lusaka'

USE_I18N = True

# USE_TZ must be True for the timezone handling in views.py (timezone.now()) to work correctly
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# --- Custom Authentication/Redirect Settings (FIXED) ---

# FIX APPLIED: Changed to 'dashboard_redirect' (the URL name for path='')
# to trigger the custom_dashboard_redirect function correctly.
LOGIN_REDIRECT_URL = 'dashboard_redirect'

# URL to redirect to after successful logout (Fixes the HTTP 405 error).
LOGOUT_REDIRECT_URL = '/'

# --- Crispy Forms Configuration ---
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"
MEDIA_ROOT = BASE_DIR / 'media'

# The URL that handles the media served from MEDIA_ROOT.
MEDIA_URL = '/media/'